backend:
  name: git-gateway
# publish_mode: editorial_workflow
media_folder: static/uploads
public_folder: uploads
show_preview_links: false

collections:
  - label: "Form"
    name: "forms"
    folder: "content/forms"
    create: true
    format: json
    preview_path: /{{slug}}
    identifier_field: path
    fields:
      - {label: "Path", name: "path", widget: "string", hint: "http://signup.falconbrands.com/$PATH"}
      - {label: "Google Sheet ID", name: "sheet", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown", required: false}
      - {label: "Background image", name: "backgroundImage", widget: "image", required: false}
      - {label: "Background color", name: "backgroundColor", widget: "string", required: false}
      - {label: "Logo", name: "logo", widget: "image", required: false}
      - {label: "Button color", name: "buttonColor", widget: "string", required: false}
      - {label: "Success message", name: "successMessage", widget: "markdown", default: "Success!"}
      - label: "Fields"
        name: "fields"
        widget: "list"
        fields:
        - {label: "Name", name: "name", widget: "string", hint: "Must relate to a column header on target Google Sheet."}
        - {label: "Label", name: "label", widget: "string"}
        - {label: "Required", name: "required", widget: "boolean", required: false}
        - label: "Type"
          name: "type"
          widget: "select"
          options: ["text", "number", "email"]
          default: ["text"]
        - label: "Width"
          name: "width"
          widget: "select"
          options: ["is-three-quarters", "is-two-thirds", "is-half", "is-one-third", "is-one-quarter", "is-full"]
          default: ["is-full"]
    editor:
        preview: false